# Global Values
repoUrl: "https://github.com/Umesh-Pagar/argocd.git"
targetRevision: HEAD
region: ""
account: ""
env: "dev"
namespace: "argocd"

# Datadog Agent Values
datadogAgent:
  enable: false
  apiKeyExistingSecret: "datadog-secret"
  site: "datadoghq.com"
  namespace: "datadog"

# External Secrets Operator
externalSecrets:
  enable: true
  namespace: "external-secrets"

esoConfig:
  enable: true
  serviceAccountName: "external-secrets-sa"
  serviceAccountNamespace: "external-secrets"
  secrets:
  - name: "datadog-secret"  # Kubernetes secret name
    namespace: "datadog"
    key: "api-key"          # Key in the secret
    remoteRef:
      aws: "datadog/api-key"   # AWS Secret Manager secret name
      azure: "datadog-api-key"   # Azure Key Vault secret name
  - name: "wiz-secret"
    namespace: "wiz"
    key: "api-token"
    remoteRef:
      aws: "wiz/api-token-test"
      azure: "wiz-api-token"

# Cluster Autoscaler Values
clusterAutoscaler:
  enable: false
  serviceAccountName:
  namespace: "cluster-autoscaler"

# nginx Values
ingressNginx:
  enable: false  
  namespace: "ingress-nginx"
  repoURL: "https://kubernetes.github.io/ingress-nginx"
  appVersion: 1.0
  controller:
    service:
      targetPorts:
        http: 80

wiz:
  enable: false
  namespace: "wiz"
  targetRevision: 0.2.37

# Metrics Server Values
metricsServer:
  enable: false
  targetRevision: 3.8.2
  namespace: "kube-system"