{{- if and (.Values.clusterAutoscaler) (.Values.clusterAutoscaler.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: autoscaler-{{ .Values.env }}
  namespace: {{ .Values.namespace }}
spec:
  goTemplate: true
  generators:
  - list:
      elements:
      {{- range .Values.clusters }}
      - clusterName: {{ .name }}
        provider: {{ .provider }}
      {{- end }} 
  template:
    metadata:
      name: 'autoscaler-{{`{{.clusterName}}`}}'
    spec:
      project: default
      source:
        repoURL: {{ .Values.repoUrl }}
        path: cluster-addons/add-ons/cluster-autoscaler
        targetRevision: {{ .Values.targetRevision }}
        helm:
          values: |
            provider: '{{`{{.provider}}`}}'
            cluster-autoscaler:
            {{- toYaml .Values.clusterAutoscaler | nindent 14 }}
          parameters:
          - name: cluster-autoscaler.awsRegion
            value: {{ .Values.region }}
          - name: cluster-autoscaler.rbac.serviceAccount.name
            value: {{ .Values.clusterAutoscaler.serviceAccountName }}
          - name: cluster-autoscaler.autoDiscovery.clusterName
            value: '{{`{{.clusterName}}`}}'
      destination:
        name: '{{`{{.clusterName}}`}}'
        namespace: {{ .Values.clusterAutoscaler.namespace }}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        retry:
          limit: 1
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 1m
{{- end -}}