{{- if and (.Values.datadogAgent) (.Values.datadogAgent.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: datadog-{{ .Values.env }}
  namespace: {{ .Values.namespace }}
spec:
  goTemplate: true
  generators:
  - list:
      elements:
      {{- range .Values.clusters }}
      - clusterName: {{ .name }}
        provider: {{ .provider }}
      {{- end }}
  template:
    metadata:
      name: 'datadog-{{`{{.clusterName}}`}}'
    spec:
      project: "default"
      source:
        repoURL: {{ .Values.datadogAgent.repoUrl }}
        chart: datadog
        targetRevision: {{ .Values.datadogAgent.targetRevision }}
        helm:
          values: |
            datadog:
              apiKeyExistingSecret: {{ .Values.datadogAgent.apiKeyExistingSecret }}
              site: {{ .Values.datadogAgent.site }}
              namespace: {{ .Values.datadogAgent.namespace }}
              logs:
                enabled: true
                containerCollectAll: true
                containerCollectUsingFiles: true
              apm:
                portEnabled: true
                socketPath: /var/run/datadog/apm.socket
                hostSocketPath: /var/run/datadog/
              processAgent:
                enabled: true
                processCollection: false
              systemProbe:
                enableTCPQueueLength: false
                enableOOMKill: true
                collectDNSStats: false
              kubeStateMetricsEnabled: true
              orchestratorExplorer:
                enabled: true
                kubelet:
                  host:
                    valueFrom:
                      fieldRef:
                        fieldPath: spec.nodeName
                  hostCAPath: /etc/kubernetes/certs/kubeletserver.crt
            providers:
              aks:
                enabled: true
            remoteConfiguration:
              enabled: true
      destination:
        name: '{{`{{.clusterName}}`}}'
        namespace: {{ .Values.datadogAgent.namespace }}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        retry:
          limit: 1
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 1m
{{- end -}}