{{- if and (.Values.wiz) (.Values.wiz.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: wiz-agent-{{ .Values.env }}
  namespace: {{ .Values.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  goTemplate: true
  generators:
  - list:
      elements:
      {{- range .Values.clusters }}
      - clusterName: {{ .name }}
        provider: {{ .provider }}
      {{- end }} 
  template:
    metadata:
      name: 'wiz-agent-{{`{{.clusterName}}`}}'
    spec:  
      project: default  # Replace with your Argo CD project name  
      source:
        path: cluster-addons/add-ons/wiz-agent 
        repoURL: {{ .Values.repoUrl }}  # The Git repository URL
        targetRevision: {{ .Values.targetRevision }}  # Replace with the desired chart version
        helm:
          values: |
            provider: '{{`{{.provider}}`}}'
            global:
              wizApiToken:
                secret:
                  create: false # We create it manually
                  name: "wiz-api-token"

            wiz-kubernetes-connector:
              enabled: true
              broker:
                enabled: true

            wiz-sensor:
              enabled: true
              imagePullSecret:
                create: false # We create it manually
                name: "sensor-image-pull"

            wiz-admission-controller:
              enabled: false

              kubernetesAuditLogsWebhook:
                enabled: false
      destination:
        namespace: {{ .Values.wiz.namespace }}  # Replace with your desired namespace
        name: '{{`{{.name}}`}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        retry:
          limit: 1
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 1m
{{- end -}}